[Unit]
Wants=audio-hw-socket.socket
After=audio-hw-socket.socket

[Service]
ExecStart=
ExecStart=/usr/libexec/pulseaudio-audio-hw-socket /usr/bin/pulseaudio --daemonize=no $CONFIG
# Expose audio_hw_socket only while PulseAudio is up, see audio-hw-socket.socket
ExecStartPost=-/bin/mv -f /dev/socket/.audio_hw_socket /dev/socket/audio_hw_socket
ExecStopPost=-/bin/mv -f /dev/socket/audio_hw_socket /dev/socket/.audio_hw_socket
